apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookmark-service
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookmark-service
  template:
    metadata:
      labels:
        app: bookmark-service
    spec:
      containers:
        - name: bookmark-service
          image: hemant1vyas/bookmark-service:latest
          ports:
            - containerPort: 9966
          env:
            - name: MONGO_USER
              value: user
            - name: MONGO_PASSWORD
              value: password
            - name: MONGO_HOST
              value: mongodb-bookmark
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_DATABASE
              value: bookmark_db
            - name: JWT_SECRET
              value: fsyfashvagsuygsqagjhabsmbqw231t67512736teuqbk32t3781
---
apiVersion: v1
kind: Service
metadata:
  name: bookmark-service
  namespace: microservices
spec:
  selector:
    app: bookmark-service
  ports:
    - port: 9966
      targetPort: 9966
      protocol: TCP
