# Persistent Volume Claim for MongoDB
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-aijob-pvc
  namespace: microservices
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
---
# MongoDB Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-aijob
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-aijob
  template:
    metadata:
      labels:
        app: mongodb-aijob
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
          args: ["--bind_ip_all"]
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: admin
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: password
            - name: MONGO_INITDB_DATABASE
              value: aijob_db
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongodb-aijob-pvc
---
# MongoDB Service
apiVersion: v1
kind: Service
metadata:
  name: mongodb-aijob
  namespace: microservices
spec:
  selector:
    app: mongodb-aijob
  ports:
    - port: 27017
      targetPort: 27017
