apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-bookmark-pvc
  namespace: microservices
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-bookmark
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-bookmark
  template:
    metadata:
      labels:
        app: mongodb-bookmark
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
          args: ["--bind_ip_all"]
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: user
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: password
            - name: MONGO_INITDB_DATABASE
              value: bookmark_db
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongodb-bookmark-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-bookmark
  namespace: microservices
spec:
  selector:
    app: mongodb-bookmark
  ports:
    - port: 27017
      targetPort: 27017
